README.md
package.json
pnpm-lock.yaml
src/lib/components/LocaleChooser.svelte
src/lib/components/Milestone.svelte
src/lib/components/Navigation/FunctionalIcon.svelte
src/lib/i18n.ts
src/lib/index.ts
src/locales/de.json
src/locales/en.json
src/routes/+layout.svelte
src/routes/+layout.ts
src/routes/milestone/+page.svelte

- add language choice to top navbar
- for now only the milestone component is available in multiple language
- text for other components can be added to the json files in the src/lib/locales folder
- another language can be added by adding a new json file to the locales folder
- uses the svelte-i18n library
- resolves #9

Add initial i18n support with en/de

---

.gitignore
frontend/src/lib/components/DataDisplay/TableDisplay.svelte
frontend/src/lib/components/DataDisplay/TableElements/TableCell.svelte
frontend/src/lib/components/DataDisplay/TableElements/TableHeader.svelte
frontend/src/lib/stores/contentStore.ts
frontend/src/routes/childLand/[userID]/[childID]/+page.js
frontend/src/routes/childLand/[userID]/[childID]/+page.svelte
frontend/src/routes/dataAcquisition/[surveyName]/+page.js
frontend/src/routes/dataAcquisition/[surveyName]/+page.svelte
frontend/src/routes/surveyfeedback/+page.svelte

- add capability to have links to the `TableCell` component
- add dummy links to the existing tables: 
- table cell with feedback: goes to milestone 
- date in table header: goes to surveyfeedback
- several async function calls did not `await`. This has been fixed
- make `<script>` with changes blocks into typescript

Make table overview more functional

---

frontend/src/lib/components/Milestone.svelte
frontend/src/routes/+layout.svelte
frontend/src/routes/milestone/+page.svelte

- milestone component cycles through available images for that milestone
- transition via opacity every 5secs
- provide list of image urls in demo data instead of a single image
- remove padding on mobile devices to use more of the screen
- resolves #51

Display multiple images in Milestone component

---

frontend/src/lib/components/DataDisplay/CardDisplay.svelte
frontend/src/lib/components/DataDisplay/GalleryDisplay.svelte
frontend/src/lib/components/MilestoneGroup.svelte
frontend/src/lib/components/MilestoneOverview.svelte
frontend/src/routes/milestonegroup/+page.svelte
frontend/src/routes/milestoneoverview/+page.svelte

- uses much the same visual buildingblocks as the milestonegroup page: `table of cards`
- uses button exposed by `CardDisplay` component to indicate status and allow for access to milestonepage
- allows for searching milestones by status or by part of header 
- displays status bar. Intention is to update it when new milestones are completed, but this has not yet been included
- uses breadcrumbs for navigation.
- adds ability to have a configurable Icon in the `CardDisplay` button 
- adds customizable `searchPlaceHolder` and seach function to the `GalleryDisplay`

Add overview page for individual milestone

---

frontend/.prettierignore
frontend/README.md
frontend/package.json
frontend/pnpm-lock.yaml
frontend/src/lib/admin.ts
frontend/src/lib/components/Admin/DeleteMilestoneGroupModal.svelte
frontend/src/lib/components/Admin/EditMilestoneGroupModal.svelte
frontend/src/lib/components/Admin/Languages.svelte
frontend/src/lib/components/Admin/MilestoneGroups.svelte
frontend/src/lib/components/Admin/NewMilestoneGroupModal.svelte
frontend/src/lib/components/LocaleChooser.svelte
frontend/src/lib/i18n.ts
frontend/src/lib/stores/adminStore.ts
frontend/src/locales/de.json
frontend/src/locales/en.json
frontend/src/routes/admin/+page.svelte
frontend/vite.config.ts
mondey_backend/src/mondey_backend/main.py
mondey_backend/src/mondey_backend/models/milestones.py
mondey_backend/src/mondey_backend/routers/admin.py
mondey_backend/src/mondey_backend/routers/milestones.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/test_admin.py
mondey_backend/tests/routers/test_milestones.py

- admin frontend
- languages can be added, deleted
- use ISO6391 library to get list of possible language codes and translate codes to native names
- milestonegroups can be added, edited, deleted
- milestone group images can be uploaded
- add lib/admin with functions to interact with API
- add adminStore with milestones
- also includes lang_id and isLoggedIn temporarily, probably these should be refactored into main site
- backend
- add Language model
- use this id instead of 2-character string to identify language
- use `(group_id,lang_id)` as primary key for MilestoneGroupText, remove separate primary key
- add endpoints to get, create and delete languages

Extend admin interface

---

mondey_backend/src/mondey_backend/settings.py
mondey_backend/src/mondey_backend/users.py

- set false by default to allow cookies over http for initial testing

Add COOKIE_SECURE setting

---

frontend/src/lib/components/Admin/Languages.svelte
mondey_backend/src/mondey_backend/databases/milestones.py
mondey_backend/src/mondey_backend/routers/admin.py
mondey_backend/tests/routers/test_admin.py

- ensures the languages database always contains the rows
- 1 de
- 2 en
- don't allow admins to delete either of these languages
- no use case where this would be required
- and could make a mess in production if it happened by accident
- remove delete button from admin interface for these languages
- resolves #126

Add de/en languages to the database on startup if there are no languages

---

mondey_backend/src/mondey_backend/models/milestones.py
mondey_backend/src/mondey_backend/models/utils.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/test_milestones.py

- sort milestones list by ascending order of `Milestone.order`
- update test data to include ordering that is not the same as the order of ids

Ensure `MilestoneGroup.milestones` is sorted correctly

---

frontend/src/lib/components/Card.svelte
frontend/src/lib/components/FrontPageCard.svelte
frontend/src/lib/components/Frontpage.svelte
frontend/src/locales/de.json
frontend/tailwind.config.ts

- Added one card to the home screen instead of the gallery (it stayed within the gallery, it is possible to add more cards if needed).

Changing the card gallery to one card on the main page

---

frontend/src/lib/admin.svelte.ts
frontend/src/lib/components/Admin/EditMilestoneGroupModal.svelte
frontend/src/lib/components/Admin/EditMilestoneModal.svelte
frontend/src/lib/components/Admin/MilestoneGroups.svelte
frontend/src/lib/components/Milestone.svelte
mondey_backend/pyproject.toml
mondey_backend/src/mondey_backend/routers/admin_routers/milestones.py
mondey_backend/src/mondey_backend/routers/users.py
mondey_backend/src/mondey_backend/routers/utils.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/admin_routers/test_admin_milestones.py
mondey_backend/tests/routers/test_users.py

- backend
- open uploaded images using pillow
- resize if width > 1024
- export to webp format using pywebp
- add some png & jpeg files to the tests
- frontend-admin
- allow png uploads as well as jpg
- frontend
- update image urls
- resolves #166

Optimise images when they are uploaded and save in webp format

---

frontend/src/lib/components/FrontPageAbout.svelte
frontend/src/lib/components/FrontPageCard.svelte
frontend/src/locales/de.json

- Changes the alignment of elements on devices with different screen sizes

fixing the alignment of elements on the front page

---

frontend/nginx.conf
frontend/src/lib/components/Admin/EditMilestoneGroupModal.svelte
frontend/src/lib/components/Admin/EditMilestoneModal.svelte
frontend/src/lib/components/DataInput/ImageFileUpload.svelte
frontend/src/lib/components/WarningModal.svelte
frontend/src/locales/de.json
mondey_backend/src/mondey_backend/routers/utils.py

- admin-frontend
- limit upload image file sizes to 2 MB for Milestone and MilestoneGroup images
- display warning modal and ignore files if too large
- frontend
- add WarningModal and ImageFileUpload components
- deployment
- set client_max_body_size to 2MB in nginx config
- backend
- remove exif orientation tag if present to avoid unexpected rotation of uploaded images in some cases
- use ImageOps.contain instead of resizing the image
- resolves #165

Limit allowed file size to 2MB for image uploads

---

mondey_backend/src/mondey_backend/routers/admin_routers/languages.py
mondey_backend/src/mondey_backend/routers/utils.py

- if parent dir is missing it is now created instead of raising an error
- resolves #180

Add `parents=True` to mkdir calls in backend

---

mondey_backend/pyproject.toml
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/admin_routers/test_admin_milestones.py

- expected age can vary by +/- 1 month depending on exact date when test runs
- this is due to making the answer session 30 days in the past, which is not always the previous month
- allow for this in the test so the test is valid regardless of the current date!

Make flaky test robust

---

.pre-commit-config.yaml
frontend/src/lib/components/Milestone.svelte
mondey_backend/src/mondey_backend/models/milestones.py
mondey_backend/src/mondey_backend/routers/milestones.py
mondey_backend/src/mondey_backend/routers/users.py
mondey_backend/src/mondey_backend/routers/utils.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/test_users.py

- MilestoneAnswer
- An answer is now created for every milestone when an answer session is created
- The initial value of the answer is `-1` which indicates the user has not yet submitted an answer for this milestone
- Add `milestone_group_id` field for convenience when calculating statistics / feedback
- get_milestone_groups
- Now returns the milestones according to the MilestoneAnswers for the current session
- This means the set of milestones is fixed and doesn't change even if a milestone expected_age changes such that it would no longer be selected for that session
- update_milestone_answer
- no longer creates an answer session if there is no existing unexpired one
- either updates the existing answer for the supplied session, or returns 404 or 401
- Milestone component
- all answers …

Fix the set of milestones when a milestone answer session is created

---

docker-compose.yml
frontend/Dockerfile
frontend/src/locales/de.json
frontend/src/routes/verify/[[code]]/+page.svelte
mondey_backend/src/mondey_backend/settings.py
mondey_backend/src/mondey_backend/users.py
mondey_backend/tests/routers/test_auth.py

- docker-compose
- add postfix image
- backend
- add SMTP_HOST to settings
- send user an email with a verification link when they sign up
- frontend
- add /verify route
- resolves #109

Add email verification

---

frontend/src/lib/components/Admin/Translations.svelte

- ensure that all sections from de are present in each translation
- if a section is missing then add it
- we don't need to add missing keys as they are created automatically
- resolves #206

Fix bug in admin translation editing

---

docker-compose.yml
mondey_backend/src/mondey_backend/main.py

- remove additional quotes in the docker compose file to make sure the backend starts correctly

Fix crontab startup issue

---

frontend/src/app.css
frontend/src/lib/components/Admin/AddButton.svelte
frontend/src/lib/components/Admin/DeleteButton.svelte
frontend/src/lib/components/Admin/EditButton.svelte
frontend/src/lib/components/Admin/MilestoneExpectedAges.svelte
frontend/src/lib/components/Admin/MilestoneGroups.svelte
frontend/src/lib/components/Admin/Questions.svelte
frontend/src/lib/components/Admin/ReorderButton.svelte
frontend/src/lib/components/Admin/SaveButton.svelte
frontend/src/lib/components/Admin/Users.svelte
frontend/src/routes/stylesPreview/+page.svelte
frontend/src/routes/userLand/children/feedback/+page.svelte
frontend/src/routes/userLand/children/gallery/+page.svelte
frontend/src/routes/userLand/children/registration/+page.svelte
frontend/src/routes/userLand/milestone/group/+page.svelte
frontend/tailwind.config.ts

Now the tailwind theme uses the blue/green teal color. Interactive parts of the site use this color, including <Buttons>, <buttons>, some form element outlines, and <a links in text form (e.g. "Forgot password" on the login page). Future flowbite svelte components, tables, accordions etc, should all work with this theming.
Additionally, milestone buttons remain with the "Blue" color.
I prioritized using tailwind theming for future flowbite component use compatibility, but some exceptions remain hardcoded in app.css, mostly for icons, a media query, and app basics. I also felt setting up SCSS might not be worth it. The tradeoff with that is that theming works great, but we are not using variables as much as ideal (For example, some hardcoded colors in the tailwind theme config are …

Standardize tailwind css buttons

---

DEPLOYMENT.md
docker-compose.yml
mondey_backend/src/mondey_backend/main.py
mondey_backend/src/mondey_backend/settings.py
mondey_backend/src/mondey_backend/users.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/test_auth.py

- backend
- add username/password for smtp server to settings
- if provided, use them when authenticating with the SMTP server
- docker-compose.yaml
- add new settings variables
- set postfix image to autogenerate DKIM keys
- deployment docs
- how to use another SMTP server to send emails
- how to use a relay host if using the docker postfix image to send emails
- how to configure SPF/DKIM/DMARC DNS settings
- resolves #288

Improve and document email deployment setup

---

frontend/src/lib/components/Admin/EditQuestionModal.svelte
frontend/src/lib/components/DataInput/DataInput.svelte
frontend/src/routes/userLand/dataInput/+page.svelte

- use `element.required` instead of hard-coding to `true`
- refactor `effect` used to update state -> `derived` state
- add utility function for parsing json list
- fix typo in css
- resolves #314

Make optional user questions optional in UI

---

mondey_backend/src/mondey_backend/statistics.py
mondey_backend/tests/conftest.py
mondey_backend/tests/routers/test_research.py
mondey_backend/tests/routers/test_users.py

- if the `answer` to a question is the `additional_option` from the question
- the user entered a free text answer `additional_answer`
- this `additional_answer` is now used instead of `answer` in the research/data endpoint
- resolves #308

Fix missing additional_answers in research data

---

frontend/src/lib/translations.ts
frontend/src/routes/userLand/research/+page.svelte
frontend/src/routes/userLand/research/dataWorker.ts
frontend/tests/ui/research.spec.ts

- milestone selection is now a multiselect
- refactor worker
- all selected milestones are now concatenated before groupby
- separate init and update messages
- use milestone and groupby names throughout (including in generated CSV file, filename, and web page)
- resolves #325

Allow selection of multiple milestones in research page

---

frontend/src/lib/components/FrontPageAbout.svelte

This closes #329 by configuring the test data on click rather than once per page load, and disables the button as a rudimentary way to prevent account creation spam.

Fix bug causing duplicate test user accounts if the user double clicked. Issue #329

---

frontend/src/lib/components/Admin/InputAutoTranslate.svelte
frontend/src/lib/components/Admin/Translations.svelte

- add `no-cache` to fetch request when getting i18n json files from server in admin interface
- otherwise we don't see the changes made until whenever the cached version is invalidated
- resolves #348
- disable auto-translate button after it is clicked to avoid spamming deepl api with requests

Fix translations not being updated

---

frontend/src/lib/components/DataDisplay/GalleryDisplay.svelte
frontend/src/routes/userLand/milestone/overview/+page.svelte

Yes we said 4 was okay on big screens, but I think the breakpoint for big is much smaller than we expect - it's essentially not much bigger than a laptop screen). Plus fix the search menu being broken for cases where there is search data.

Remove paragraph from milestones + Make 2-3 columns appear depending on screen size

---

mondey_backend/src/mondey_backend/logging.py
mondey_backend/src/mondey_backend/main.py
mondey_backend/src/mondey_backend/routers/scores.py
mondey_backend/src/mondey_backend/routers/users.py
mondey_backend/src/mondey_backend/routers/utils.py
mondey_backend/src/mondey_backend/statistics.py
mondey_backend/src/mondey_backend/users.py

- ignore the answer if the child has a negative age
- also only calculate agescorecollections for ages <= 72
- note: do `drop table milestoneagescorecollection; drop table milestonegroupagescorecollection;` before running this commit
- resolves #371
Also centralise logging, remove some leftover debugging logging output

Fix bug in stats update caused by negative age child

---

mondey_backend/src/mondey_backend/statistics.py

- refactor how existing stats are updated in the database
- resolves #378
- `analyse_answer_session` now sets `completed=False` for a session which was `completed=True` if it finds an unanswered milestone in the session
- shouldn't happen for `completed` sessions created by users on the website but may possibly occur with imported data
- this avoids the possibility of `-1` scores messing up the statistics calculations

Fix bug in stats update

---

frontend/nginx.conf

- increase the read timeout to 10 minutes to allow for potentially slow update stats endpoint call
- resolves #394

Increase nginx proxy timeout for /api reads

---

frontend/src/lib/components/DataDisplay/CardDisplay.svelte
frontend/src/lib/translations.ts
frontend/src/routes/userLand/children/feedback/+page.svelte
frontend/src/routes/userLand/children/registration/+page.svelte
frontend/src/routes/userLand/dataInput/+page.svelte
frontend/src/routes/userLand/milestone/+page.svelte
frontend/src/routes/userLand/milestone/group/+page.svelte
frontend/src/routes/userLand/milestone/overview/+page.svelte

- /children/feedback
- don't display error if there are no answer sessions yet
- /milestone/* and /children/*
- redirect to /children if necessary data is missing (e.g. if user refreshed)
- resolves various cases where opening a saved link or refreshing the page results in a broken website state
- resolves #256

Improve navigation errors

---

frontend/src/routes/userLand/milestone/+page.svelte

- use fixed relative width layout on desktop: 1/5 image, 3/5 text, 1/5 buttons
- resolves issue where image width would change when text changes or beobachtungshinweise was unfolded/folded
- set image width for each breakpoint such that most of the image is not cropped
- resolves issue where for some screen sizes the image would be very narrow with most of the content cropped

Improve milestone image sizing

---

frontend/src/routes/+layout.svelte

@lkeegan Please can you put this into production so we can test it with real phones?
This might be why the iPhone width doesn't display correctly.

Add viewport meta tag for iPhones to avoid width bug

---

DEPLOYMENT.md
docker-compose.yml
mondey_backend/src/mondey_backend/models/milestones.py
mondey_backend/src/mondey_backend/models/questions.py
mondey_backend/src/mondey_backend/models/utils.py
mondey_backend/src/mondey_backend/routers/utils.py

- add docker-postgres-backup-local images to docker-compose
- does daily local backups of the databases
- periodically removes old backups
- document how to restore from one of these backups in DEPLOYMENT.md
- resolves 280
Also
- minor refactor of database models for clarity
- add `list_relationship` for relationship with delete cascade
- use this instead of `back_propagates` with delete cascade as additional kwargs
- fix bug in session_remaining_seconds calculation
- it should go down as time goes by, not up!

Add daily database backups
